# fly.toml app configuration file generated for loldle-bot on 2026-01-11T20:41:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'loldle-bot'
primary_region = 'ewr'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
